-- =====================================================================
-- Nomes em portugues para os exercicios mais usados na academia.
-- Aplicado apenas onde ainda nao existe traducao.
-- =====================================================================

UPDATE exercises e
SET name_pt = v.pt
FROM (VALUES
    -- ------------------------------- peito -------------------------------
    ('Incline Bench Press - Barbell',   'Supino inclinado com barra'),
    ('Incline Bench Press - MP',        'Supino inclinado na máquina'),
    ('Legend Incline Bench Press',      'Supino inclinado (Legend)'),
    ('Seated Bench Press',              'Supino sentado na máquina'),
    ('Flat Machine Press',              'Supino reto na máquina'),
    ('Chest Press',                     'Chest press (máquina)'),
    ('Leverage Machine Chest Press',    'Supino na máquina articulada'),
    ('Legend Chest Press',              'Chest press (Legend)'),
    ('Pec Deck',                        'Voador (peck deck)'),
    ('Machine chest fly',               'Voador na máquina'),
    ('Fly With Cable',                  'Crucifixo no cabo'),
    ('Fly With Dumbbells',              'Crucifixo com halteres'),
    ('Cable Cross-over',                'Crossover na polia'),
    ('Low Pulley Cable Fly',            'Crucifixo na polia baixa'),
    ('Cable Fly Upper Chest',           'Crucifixo no cabo (peito superior)'),
    ('Cable Fly Middle Chest',          'Crucifixo no cabo (peito médio)'),
    ('Cable Fly Lower Chest',           'Crucifixo no cabo (peito inferior)'),
    ('Seated Cable chest fly',          'Crucifixo sentado na polia'),
    ('Dumbbell Floor Press',            'Supino no chão com halteres'),
    ('Decline Bench Press Dumbbell',    'Supino declinado com halteres'),
    ('Dumbbell Hex Press',              'Supino hex com halteres'),
    ('Push-Ups | Incline',              'Flexão inclinada'),
    ('Push-Ups | Decline',              'Flexão declinada'),
    ('Diamond push ups',                'Flexão diamante'),
    ('knee push-ups',                   'Flexão com apoio dos joelhos'),
    ('Weighted push-ups',               'Flexão com carga'),
    ('Close-grip Press-ups',            'Flexão pegada fechada'),
    ('Dips Between Two Benches',        'Mergulho entre bancos'),
    ('Bench Dips On Floor HD',          'Mergulho no banco'),
    ('Ring Dips',                       'Paralelas nas argolas'),
    ('Chair dips',                      'Mergulho na cadeira'),
    ('Reverse Grip Bench Press',        'Supino pegada supinada'),
    ('Pause Bench',                     'Supino com pausa'),

    -- ------------------------------- costas ------------------------------
    ('Underhand Lat Pull Down',         'Puxada supinada'),
    ('Close-grip Lat Pull Down',        'Puxada pegada fechada'),
    ('Inverted Lat Pull Down',          'Puxada invertida'),
    ('Wide-grip Pulldown',              'Puxada pegada aberta'),
    ('Neutral Grip Lat Pulldown',       'Puxada pegada neutra'),
    ('V-Bar Pulldown',                  'Puxada com triângulo'),
    ('Single-Arm Lat Pulldown',         'Puxada unilateral'),
    ('Lat Pull Down (Leaning Back)',    'Puxada com tronco inclinado'),
    ('Straight-Arm Pulldown (Cable)',   'Pulldown com braços estendidos'),
    ('Seated Cable Row',                'Remada baixa no cabo'),
    ('Seated Row (Machine)',            'Remada sentado na máquina'),
    ('Seated V-Grip Row',               'Remada com triângulo'),
    ('Rowing, T-bar',                   'Remada cavalinho (T-bar)'),
    ('Rowing, Lying on Bench',          'Remada deitado no banco'),
    ('Rowing seated, narrow grip',      'Remada sentado pegada fechada'),
    ('Bent Over Dumbbell Rows',         'Remada curvada com halteres'),
    ('Barbell Row (Overhand)',          'Remada curvada pronada'),
    ('Barbell Row (Underhand)',         'Remada curvada supinada'),
    ('One Arm Bent Row',                'Remada unilateral curvada'),
    ('One-Arm Heavy Row',               'Remada unilateral pesada'),
    ('Single arm row',                  'Remada unilateral'),
    ('Low row',                         'Remada baixa'),
    ('High Row',                        'Remada alta na máquina'),
    ('Inverted Rows',                   'Remada invertida'),
    ('TRX Rows',                        'Remada no TRX'),
    ('Renegade Row',                    'Remada renegada'),
    ('Meadows Row',                     'Remada Meadows'),
    ('Helms Row',                       'Remada Helms'),
    ('Kroc Row',                        'Remada Kroc'),
    ('Incline Dumbbell Row',            'Remada inclinada com halteres'),
    ('Leverage Machine Iso Row',        'Remada na máquina articulada'),
    ('Pullover Machine',                'Pullover na máquina'),
    ('Cross-Bench Dumbbell Pullovers',  'Pullover com halter no banco'),
    ('High-pulley pullover',            'Pullover na polia alta'),
    ('Chin Up',                         'Barra fixa supinada'),
    ('Pull-Ups (Wide Grip)',            'Barra fixa pegada aberta'),
    ('Pull-Ups (Neutral Grip)',         'Barra fixa pegada neutra'),
    ('Assisted Pull-Up',                'Barra fixa assistida'),
    ('Assisted chin-ups',               'Barra fixa supinada assistida'),
    ('Muscle up',                       'Muscle up'),
    ('Deficit Deadlift',                'Levantamento terra com déficit'),
    ('Speed Deadlift',                  'Levantamento terra explosivo'),
    ('Rack Deadlift',                   'Levantamento terra no rack'),
    ('Sumo Deadlift',                   'Levantamento terra sumô'),
    ('Dumbbell Romanian Deadlift',      'Terra romeno com halteres'),
    ('Dumbbell Deadlift',               'Levantamento terra com halteres'),
    ('Stiff-legged Deadlifts',          'Stiff'),
    ('Good Morning',                    'Good morning'),
    ('Reverse Hyperextension',          'Hiperextensão invertida'),
    ('Lower Back Extensions',           'Extensão lombar'),
    ('Shrugs, Barbells',                'Encolhimento com barra'),
    ('Shrugs, Dumbbells',               'Encolhimento com halteres'),
    ('Shoulder Shrug',                  'Encolhimento de ombros'),
    ('Shrugs on Multipress',            'Encolhimento no multipress'),

    -- ------------------------------- pernas ------------------------------
    ('Front Squats',                    'Agachamento frontal'),
    ('Hack Squats',                     'Agachamento hack'),
    ('Barbell Hack Squats',             'Agachamento hack com barra'),
    ('Box squat',                       'Agachamento no caixote'),
    ('Smith machine squat',             'Agachamento no Smith'),
    ('Squats on Multipress',            'Agachamento no multipress'),
    ('Bulgarian Squat with Dumbbells',  'Agachamento búlgaro com halteres'),
    ('Dumbbell Goblet Squat',           'Agachamento goblet'),
    ('Dumbbell Front Squat',            'Agachamento frontal com halteres'),
    ('Overhead Squat',                  'Agachamento overhead'),
    ('Pendulum Squat',                  'Agachamento pendular'),
    ('Belt Squat',                      'Agachamento no cinto'),
    ('Trap Bar Squat',                  'Agachamento na trap bar'),
    ('Prisoner Squat',                  'Agachamento prisioneiro'),
    ('Bodyweight Squat HD',             'Agachamento livre (peso corporal)'),
    ('Slow Squat',                      'Agachamento lento'),
    ('Cossack squat',                   'Agachamento cossaco'),
    ('Leg Presses (wide)',              'Leg press pegada aberta'),
    ('Leg Presses (narrow)',            'Leg press pegada fechada'),
    ('Single Leg Extension',            'Cadeira extensora unilateral'),
    ('Leg Curls (laying)',              'Mesa flexora'),
    ('Leg Curls (sitting)',             'Cadeira flexora'),
    ('Leg Curls (standing)',            'Flexora em pé'),
    ('Nordic Curl',                     'Nordic curl'),
    ('Glute-Ham Raise',                 'Glute ham raise'),
    ('Single Leg RDL',                  'Terra romeno unilateral'),
    ('Dumbbell Split Squat',            'Afundo com halteres (split squat)'),
    ('Smith Machine Split Squat',       'Afundo no Smith'),
    ('Dumbbell Lunges Walking',         'Afundo caminhando com halteres'),
    ('Dumbbell Lunges Standing',        'Afundo com halteres'),
    ('Barbell Lunges Walking',          'Afundo caminhando com barra'),
    ('Barbell Lunges Standing',         'Afundo com barra'),
    ('Reverse lunges',                  'Afundo reverso'),
    ('Alternate back lunges',           'Afundo reverso alternado'),
    ('Weighted Step-ups',               'Step-up com peso'),
    ('Unilateral Hip Thrust',           'Elevação pélvica unilateral'),
    ('Dumbbell Hip Thrust',             'Elevação pélvica com halter'),
    ('Glute Bridge',                    'Ponte de glúteos'),
    ('Single Leg Glute Bridge',         'Ponte de glúteos unilateral'),
    ('Glute Kickback (Machine)',        'Glúteo na máquina'),
    ('Glute Drive',                     'Glute drive'),
    ('Machine Hip Abduction',           'Abdutora na máquina'),
    ('Seated Hip Abduction',            'Cadeira abdutora'),
    ('Seated Hip Adduction',            'Cadeira adutora'),
    ('Standing Calf Raises',            'Panturrilha em pé'),
    ('Sitting Calf Raises',             'Panturrilha sentado'),
    ('Seated Dumbbell Calf Raise',      'Panturrilha sentado com halteres'),
    ('Double Leg Calf Raise',           'Panturrilha bilateral'),
    ('Leg Press Toe Press',             'Panturrilha no leg press'),
    ('Squat Jumps',                     'Agachamento com salto'),
    ('box jumps',                       'Salto na caixa'),
    ('Tibialis raises',                 'Elevação de tibial'),

    -- ------------------------------- ombros ------------------------------
    ('Overhead Barbell Press',          'Desenvolvimento com barra'),
    ('Shoulder Press, Barbell',         'Desenvolvimento com barra'),
    ('Shoulder Press, Dumbbells',       'Desenvolvimento com halteres'),
    ('Shoulder Press, on Machine',      'Desenvolvimento na máquina'),
    ('Shoulder Press, on Multi Press',  'Desenvolvimento no multipress'),
    ('Arnold Shoulder Press',           'Desenvolvimento Arnold'),
    ('Push Press',                      'Push press'),
    ('Military Press mit SZ-Bar',       'Desenvolvimento militar com barra W'),
    ('Machine Side Lateral Raises',     'Elevação lateral na máquina'),
    ('Machine Lateral Raise',           'Elevação lateral na máquina'),
    ('Side Lateral Raise (Cable)',      'Elevação lateral na polia'),
    ('Cable Lateral Raises (Single Arm)', 'Elevação lateral unilateral na polia'),
    ('Seated Dumbbell Side Lateral',    'Elevação lateral sentado'),
    ('High-Cable Lateral Raise',        'Elevação lateral na polia alta'),
    ('Front Raise (Cable)',             'Elevação frontal na polia'),
    ('Front Raises with Plates',        'Elevação frontal com anilha'),
    ('Shoulder Raise (Dumbbell)',       'Elevação frontal com halteres'),
    ('Rear Delt Raises',                'Elevação posterior de ombro'),
    ('Seated rear delt rise',           'Elevação posterior sentado'),
    ('Cable Rear Delt Fly',             'Crucifixo inverso na polia'),
    ('Reverse Fly Standing',            'Crucifixo inverso em pé'),
    ('Reverse Cable Flye',              'Crucifixo inverso no cabo'),
    ('Pec deck rear delt fly',          'Voador inverso'),
    ('Incline Bench Reverse Fly',       'Crucifixo inverso no banco inclinado'),
    ('Bent-over Lateral Raises',        'Elevação lateral curvado'),
    ('Dumbbell rear delt row',          'Remada para posterior de ombro'),
    ('Upright Row, SZ-bar',             'Remada alta com barra W'),
    ('Upright Row w/ Dumbbells',        'Remada alta com halteres'),
    ('Upright Row, on Multi Press',     'Remada alta no multipress'),
    ('Facepull',                        'Face pull'),
    ('Dumbbell Bent Over Face Pull',    'Face pull com halteres'),
    ('Cable External Rotation',         'Rotação externa na polia'),
    ('Band pull-aparts',                'Abertura com elástico'),

    -- ------------------------------- braços ------------------------------
    ('Dumbbell Curl',                   'Rosca alternada com halteres'),
    ('Standing Bicep Curl',             'Rosca direta em pé'),
    ('Alternating bicep curls',         'Rosca alternada'),
    ('Biceps Curl Machine',             'Rosca na máquina'),
    ('Biceps Curl With Cable',          'Rosca na polia'),
    ('Cable Curls',                     'Rosca na polia'),
    ('Straight Bar Cable Curls',        'Rosca na polia com barra reta'),
    ('Overhand Cable Curl',             'Rosca pronada na polia'),
    ('Preacher Curls',                  'Rosca Scott'),
    ('Single-arm Preacher Curl',        'Rosca Scott unilateral'),
    ('Dumbbells on Scott Machine',      'Rosca Scott com halteres'),
    ('Dumbbell Concentration Curl',     'Rosca concentrada'),
    ('Cable Concentration Curl',        'Rosca concentrada na polia'),
    ('Spider Curl',                     'Rosca spider'),
    ('Dumbbell Incline Curl',           'Rosca inclinada com halteres'),
    ('Seated Dumbbell Curls',           'Rosca sentado com halteres'),
    ('Lying Dumbbell Curls',            'Rosca deitado com halteres'),
    ('Reverse Curl',                    'Rosca inversa'),
    ('Reverse Bar Curl',                'Rosca inversa com barra'),
    ('Reverse Grip Barbell Curls',      'Rosca inversa com barra'),
    ('Zottman curl',                    'Rosca Zottman'),
    ('Drop Curl',                       'Rosca drop'),
    ('Bayesian Curl',                   'Rosca bayesiana'),
    ('Dumbbell drag curls',             'Rosca drag'),
    ('Hammercurls on Cable',            'Rosca martelo na polia'),
    ('Bodyweight Biceps Curl',          'Rosca com peso corporal'),
    ('Triceps Pushdown',                'Tríceps pulley'),
    ('Tricep Pushdown on Cable',        'Tríceps na polia'),
    ('Tricep Rope Pushdowns',           'Tríceps corda'),
    ('Triceps Extensions on Cable',     'Tríceps na polia'),
    ('Single-arm cable pushdown',       'Tríceps unilateral na polia'),
    ('Rocking Triceps Pushdown',        'Tríceps pulley inclinado'),
    ('Drag Pushdown',                   'Tríceps drag'),
    ('Skullcrusher SZ-bar',             'Tríceps testa com barra W'),
    ('Skullcrusher Dumbbells',          'Tríceps testa com halteres'),
    ('Floor Skull Crusher',             'Tríceps testa no chão'),
    ('Incline Skull Crush',             'Tríceps testa inclinado'),
    ('Lying Triceps Extensions',        'Tríceps testa'),
    ('Overhead Triceps Extension',      'Tríceps francês'),
    ('Triceps Overhead (Dumbbell)',     'Tríceps francês com halter'),
    ('Dumbbell Triceps Extension',      'Tríceps francês com halter'),
    ('Barbell Triceps Extension',       'Tríceps testa com barra'),
    ('Seated Triceps Press',            'Tríceps francês sentado'),
    ('Triceps on Machine',              'Tríceps na máquina'),
    ('Cable Triceps Press',             'Tríceps na polia'),
    ('Tricep Dumbbell Kickback',        'Tríceps coice'),
    ('Cable Tricep Kickback',           'Tríceps coice na polia'),
    ('Lying Triceps Kickback',          'Tríceps coice deitado'),
    ('Triceps Dips (Assisted)',         'Mergulho assistido'),
    ('TRX Tricep Extension',            'Tríceps no TRX'),
    ('JM Press',                        'JM press'),
    ('Wrist curl, dumbbells',           'Rosca de punho com halteres'),
    ('Wrist curl, cable',               'Rosca de punho na polia'),
    ('Barbell Reverse Wrist Curl',      'Rosca de punho inversa'),
    ('Hand Grip',                       'Hand grip'),

    -- ----------------------------- abdômen -------------------------------
    ('Abdominal Crunch',                'Abdominal crunch'),
    ('Crunches With Cable',             'Abdominal na polia'),
    ('Crunches on Machine',             'Abdominal na máquina'),
    ('Crunches With Legs Up',           'Abdominal com pernas elevadas'),
    ('Incline Crunches',                'Abdominal inclinado'),
    ('Reverse crunch',                  'Abdominal invertido'),
    ('bicycle crunches',                'Abdominal bicicleta'),
    ('Ball crunches',                   'Abdominal na bola'),
    ('Weighted Crunch',                 'Abdominal com carga'),
    ('Dumbbell Crunches',               'Abdominal com halter'),
    ('Roman Chair Crunch',              'Abdominal na cadeira romana'),
    ('Hanging Leg Raises',              'Elevação de pernas suspenso'),
    ('Leg Raises, Lying',               'Elevação de pernas deitado'),
    ('Leg Raises, Standing',            'Elevação de pernas em pé'),
    ('Decline Bench Leg Raise',         'Elevação de pernas declinado'),
    ('Knee Raises',                     'Elevação de joelhos'),
    ('Toes to bar',                     'Toes to bar'),
    ('Front Plank',                     'Prancha frontal'),
    ('High plank',                      'Prancha alta'),
    ('Side Crunch',                     'Abdominal oblíquo'),
    ('Standing Side Crunches',          'Abdominal oblíquo em pé'),
    ('Side bend',                       'Flexão lateral de tronco'),
    ('Dumbbell Side Bend',              'Flexão lateral com halter'),
    ('Side Bends on Machine',           'Flexão lateral na máquina'),
    ('Pallof Press',                    'Pallof press'),
    ('Cable Woodchoppers',              'Lenhador na polia'),
    ('Reverse Wood Chops',              'Lenhador invertido'),
    ('Rotary Torso Machine',            'Rotação de tronco na máquina'),
    ('Trunk Rotation With Cable',       'Rotação de tronco na polia'),
    ('Hollow Hold',                     'Hollow hold'),
    ('Deadbug',                         'Dead bug'),
    ('Superman',                        'Superman'),
    ('Flutter Kicks',                   'Tesoura'),
    ('Scissors',                        'Tesoura'),
    ('Ab wheel',                        'Roda abdominal'),
    ('Barbell Ab Rollout',              'Rollout com barra'),
    ('TRX roll out',                    'Rollout no TRX'),
    ('Heel Touches',                    'Toque no calcanhar'),
    ('Medicine ball twist',             'Rotação com medicine ball'),

    -- ------------------------------ cardio -------------------------------
    ('Jogging',                         'Corrida leve'),
    ('Run',                             'Corrida'),
    ('Run - Treadmill',                 'Corrida na esteira'),
    ('Run - Interval Training',          'Corrida intervalada'),
    ('Treadmill Cardio',                'Esteira'),
    ('Stationary Bike',                 'Bicicleta ergométrica'),
    ('Stationary bike cardio',          'Bicicleta ergométrica'),
    ('Recumbent Bike',                  'Bicicleta horizontal'),
    ('Cycling cardio session',          'Pedalada'),
    ('Elliptical',                      'Elíptico'),
    ('Rowing Machine',                  'Remo ergômetro'),
    ('Stair Master',                    'Escada (stair master)'),
    ('ClimbMill',                       'Escada rolante (climbmill)'),
    ('Ski Machine',                     'Ski erg'),
    ('Skipping - Standard',             'Pular corda'),
    ('Walking',                         'Caminhada'),
    ('Battle Ropes',                    'Corda naval'),
    ('Sled Push',                       'Empurrar trenó'),
    ('Thruster',                        'Thruster'),
    ('Dumbbell Thruster',               'Thruster com halteres'),
    ('Turkish Get-Up',                  'Turkish get-up'),
    ('Suitcase Carry',                  'Caminhada com mala'),
    ('High Knee Jumps',                 'Corrida com joelhos altos'),
    ('Marching High Knees',             'Marcha com joelhos altos'),
    ('Jumping Jack HD',                 'Polichinelo'),
    ('Step Jack',                       'Polichinelo com passada'),
    ('Wall balls',                      'Wall ball'),
    ('Ball Slams',                      'Slam ball'),
    ('2 Handed Kettlebell Swing',       'Kettlebell swing com duas mãos'),
    ('Clean and Press',                 'Clean and press'),
    ('Barbell Clean and press',         'Clean and press com barra'),
    ('Snatch',                          'Arranco (snatch)'),
    ('dumbbell snatch',                 'Arranco com halter'),
    ('Clean',                           'Clean'),
    ('Bear crawl pull through',         'Bear crawl')
) AS v(en, pt)
WHERE LOWER(e.name) = LOWER(v.en)
  AND (e.name_pt IS NULL OR e.name_pt = '');
